// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbDV3aIdyy992gLyjswSHXr2l62xgaS4',
    appId: '1:990590124235:web:06711a640ec25f16b71b4e',
    messagingSenderId: '990590124235',
    projectId: 'easystudy-e0b70',
    authDomain: 'easystudy-e0b70.firebaseapp.com',
    storageBucket: 'easystudy-e0b70.firebasestorage.app',
    measurementId: 'G-GPB57ZW0DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Sn0XzRnS4FwsByPjrLyC_KssieRxwOI',
    appId: '1:990590124235:android:8388a68b5592668db71b4e',
    messagingSenderId: '990590124235',
    projectId: 'easystudy-e0b70',
    storageBucket: 'easystudy-e0b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHyOf1HkM90sFa_TnX64o2A7Cos2-3Vg',
    appId: '1:990590124235:ios:3045b2756ae066fbb71b4e',
    messagingSenderId: '990590124235',
    projectId: 'easystudy-e0b70',
    storageBucket: 'easystudy-e0b70.firebasestorage.app',
    iosBundleId: 'com.broketheframe.easystudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHyOf1HkM90sFa_TnX64o2A7Cos2-3Vg',
    appId: '1:990590124235:ios:3045b2756ae066fbb71b4e',
    messagingSenderId: '990590124235',
    projectId: 'easystudy-e0b70',
    storageBucket: 'easystudy-e0b70.firebasestorage.app',
    iosBundleId: 'com.broketheframe.easystudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdbDV3aIdyy992gLyjswSHXr2l62xgaS4',
    appId: '1:990590124235:web:45dc25f831ac9782b71b4e',
    messagingSenderId: '990590124235',
    projectId: 'easystudy-e0b70',
    authDomain: 'easystudy-e0b70.firebaseapp.com',
    storageBucket: 'easystudy-e0b70.firebasestorage.app',
    measurementId: 'G-CCWJL25W1Y',
  );
}
